# Generated by Django 3.0.8 on 2020-07-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_view', models.ImageField(upload_to='')),
                ('room_price', models.IntegerField()),
                ('hotel_name', models.CharField(max_length=200)),
                ('hotel_location', models.CharField(max_length=200)),
            ],
        ),
    ]
