# Generated by Django 3.0.8 on 2020-07-06 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lagoona_app', '0002_headermenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_view',
        ),
        migrations.AddField(
            model_name='hotel',
            name='image_url',
            field=models.CharField(default='dfault_title', max_length=200),
            preserve_default=False,
        ),
    ]
