# Generated by Django 3.0.8 on 2020-07-06 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lagoona_app', '0003_auto_20200706_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='rating',
            field=models.IntegerField(default=5, max_length=5),
            preserve_default=False,
        ),
    ]
